---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: kube-system
spec:
  interval: 60m
  releaseName: nginx
  chart:
    spec:
      chart: nginx
      version: 0.4.1
      sourceRef:
        kind: HelmRepository
        name: nginx
      interval: 30m
  values:
    controller:
      service:
        type: LoadBalancer
      metrics:
        enabled: false
