---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
spec:
  interval: 60m
  releaseName: prometheus
  chart:
    spec:
      chart: prometheus
      version:
      sourceRef:
        kind: HelmRepository
        name: 
  values:
    alertmanager:
      enabled: true
      configMapOverrideName: alertmanager
    pushgateway:
      enabled: false
    serverFiles:
      alerts:
        groups:
          - name: HostDown
            rules:
              - alert: HostDown
                expr: count(up) == 0
                for: 1m
                annotations:
                  summary: test
          - name: HostUp
            rules:
              - alert: HostUp
                expr: count(up) >= 1
                for: 1m
                annotations:
                  summary: test

---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
    name: prometheus
spec:
    providerRef:
        name: slack
    eventSeverity: info
    eventSources:
    - kind: HelmRelease
      name: prometheus
