default:

master:
  # kubeadm init --pod-network-cidr=192.168.0.0/16
	# # setup and configure the AWS Cloud Controller for the master
	#
	# KUBECONFIG=/etc/kubernetes/admin.conf kubectl apply -f https://docs.projectcalico.org/v3.2/getting-started/kubernetes/installation/hosted/etcd.yaml
	# kubectl apply -f https://docs.projectcalico.org/v3.2/getting-started/kubernetes/installation/rbac.yaml
	# kubectl apply -f https://docs.projectcalico.org/v3.2/getting-started/kubernetes/installation/hosted/calico.yaml
  # kubectl get pods --all-namespaces
	# kubectl get nodes
	# certification authentication will override the iam authenticator in the server authentication

nodes:
  # kubeadm join ...
	# example to merge into kubeadm if possible and if not kubelet direct
	# kubedns ip configuration
